title: Taqtyle - A Mesaba Finance Company
description: >- # this means to ignore newlines until "baseurl:"
  Reimagining urban living in LoHi
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: assets/css/_sass

  # data for privacy policy
address:
  name: Taqtyle
  street: "1041 Grand Ave #300"
  city: St. Paul
  state: Minnesota
  zip: 55105
  country: United States
  phone: +1 (651) 800-1977

privacy:
  hubspot: true
  formspark: true
